/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    403: (typeof import('./src/components/error/403.vue'))['default']
    404: (typeof import('./src/components/error/404.vue'))['default']
    500: (typeof import('./src/components/error/500.vue'))['default']
    ElButton: (typeof import('element-plus/es'))['ElButton']
    ElForm: (typeof import('element-plus/es'))['ElForm']
    ElFormItem: (typeof import('element-plus/es'))['ElFormItem']
    ElIcon: (typeof import('element-plus/es'))['ElIcon']
    ElInput: (typeof import('element-plus/es'))['ElInput']
    ElSwitch: (typeof import('element-plus/es'))['ElSwitch']
    LoginForm: (typeof import('./src/components/loginForm/loginForm.vue'))['default']
    RouterLink: (typeof import('vue-router'))['RouterLink']
    RouterView: (typeof import('vue-router'))['RouterView']
    SwitchDark: (typeof import('./src/components/switchDark/switchDark.vue'))['default']
  }
}
