/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    403: (typeof import('./src/components/error/403.vue'))['default']
    404: (typeof import('./src/components/error/404.vue'))['default']
    500: (typeof import('./src/components/error/500.vue'))['default']
    ElAside: (typeof import('element-plus/es'))['ElAside']
    ElAutocomplete: (typeof import('element-plus/es'))['ElAutocomplete']
    ElBadge: (typeof import('element-plus/es'))['ElBadge']
    ElBreadcrumb: (typeof import('element-plus/es'))['ElBreadcrumb']
    ElBreadcrumbItem: (typeof import('element-plus/es'))['ElBreadcrumbItem']
    ElButton: (typeof import('element-plus/es'))['ElButton']
    ElContainer: (typeof import('element-plus/es'))['ElContainer']
    ElDialog: (typeof import('element-plus/es'))['ElDialog']
    ElDropdown: (typeof import('element-plus/es'))['ElDropdown']
    ElDropdownItem: (typeof import('element-plus/es'))['ElDropdownItem']
    ElDropdownMenu: (typeof import('element-plus/es'))['ElDropdownMenu']
    ElFooter: (typeof import('element-plus/es'))['ElFooter']
    ElForm: (typeof import('element-plus/es'))['ElForm']
    ElFormItem: (typeof import('element-plus/es'))['ElFormItem']
    ElHeader: (typeof import('element-plus/es'))['ElHeader']
    ElIcon: (typeof import('element-plus/es'))['ElIcon']
    ElInput: (typeof import('element-plus/es'))['ElInput']
    ElMain: (typeof import('element-plus/es'))['ElMain']
    ElMenu: (typeof import('element-plus/es'))['ElMenu']
    ElMenuItem: (typeof import('element-plus/es'))['ElMenuItem']
    ElPopover: (typeof import('element-plus/es'))['ElPopover']
    ElScrollbar: (typeof import('element-plus/es'))['ElScrollbar']
    ElSubMenu: (typeof import('element-plus/es'))['ElSubMenu']
    ElSwitch: (typeof import('element-plus/es'))['ElSwitch']
    ElTabPane: (typeof import('element-plus/es'))['ElTabPane']
    ElTabs: (typeof import('element-plus/es'))['ElTabs']
    LoginForm: (typeof import('./src/components/loginForm/loginForm.vue'))['default']
    RouterLink: (typeof import('vue-router'))['RouterLink']
    RouterView: (typeof import('vue-router'))['RouterView']
    SwitchDark: (typeof import('./src/components/switchDark/switchDark.vue'))['default']
  }
}
