/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    403: (typeof import('./src/components/error/403.vue'))['default']
    404: (typeof import('./src/components/error/404.vue'))['default']
    500: (typeof import('./src/components/error/500.vue'))['default']
    ElSwitch: (typeof import('element-plus/es'))['ElSwitch']
    RouterLink: (typeof import('vue-router'))['RouterLink']
    RouterView: (typeof import('vue-router'))['RouterView']
    SwitchDark: (typeof import('./src/components/stwitchDark/switchDark.vue'))['default']
  }
}
